require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::CompaniesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::Company. As you add validations to Admin::Company, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::CompaniesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all admin_companies as @admin_companies" do
      company = Admin::Company.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:admin_companies)).to eq([company])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_company as @admin_company" do
      company = Admin::Company.create! valid_attributes
      get :show, {:id => company.to_param}, valid_session
      expect(assigns(:admin_company)).to eq(company)
    end
  end

  describe "GET new" do
    it "assigns a new admin_company as @admin_company" do
      get :new, {}, valid_session
      expect(assigns(:admin_company)).to be_a_new(Admin::Company)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_company as @admin_company" do
      company = Admin::Company.create! valid_attributes
      get :edit, {:id => company.to_param}, valid_session
      expect(assigns(:admin_company)).to eq(company)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::Company" do
        expect {
          post :create, {:admin_company => valid_attributes}, valid_session
        }.to change(Admin::Company, :count).by(1)
      end

      it "assigns a newly created admin_company as @admin_company" do
        post :create, {:admin_company => valid_attributes}, valid_session
        expect(assigns(:admin_company)).to be_a(Admin::Company)
        expect(assigns(:admin_company)).to be_persisted
      end

      it "redirects to the created admin_company" do
        post :create, {:admin_company => valid_attributes}, valid_session
        expect(response).to redirect_to(Admin::Company.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_company as @admin_company" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Company.any_instance.stub(:save).and_return(false)
        post :create, {:admin_company => { "name" => "invalid value" }}, valid_session
        expect(assigns(:admin_company)).to be_a_new(Admin::Company)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Company.any_instance.stub(:save).and_return(false)
        post :create, {:admin_company => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_company" do
        company = Admin::Company.create! valid_attributes
        # Assuming there are no other admin_companies in the database, this
        # specifies that the Admin::Company created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Admin::Company).to receive(:update).with({ "name" => "MyString" })
        put :update, {:id => company.to_param, :admin_company => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested admin_company as @admin_company" do
        company = Admin::Company.create! valid_attributes
        put :update, {:id => company.to_param, :admin_company => valid_attributes}, valid_session
        expect(assigns(:admin_company)).to eq(company)
      end

      it "redirects to the admin_company" do
        company = Admin::Company.create! valid_attributes
        put :update, {:id => company.to_param, :admin_company => valid_attributes}, valid_session
        expect(response).to redirect_to(company)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_company as @admin_company" do
        company = Admin::Company.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Company.any_instance.stub(:save).and_return(false)
        put :update, {:id => company.to_param, :admin_company => { "name" => "invalid value" }}, valid_session
        expect(assigns(:admin_company)).to eq(company)
      end

      it "re-renders the 'edit' template" do
        company = Admin::Company.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::Company.any_instance.stub(:save).and_return(false)
        put :update, {:id => company.to_param, :admin_company => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_company" do
      company = Admin::Company.create! valid_attributes
      expect {
        delete :destroy, {:id => company.to_param}, valid_session
      }.to change(Admin::Company, :count).by(-1)
    end

    it "redirects to the admin_companies list" do
      company = Admin::Company.create! valid_attributes
      delete :destroy, {:id => company.to_param}, valid_session
      expect(response).to redirect_to(admin_companies_url)
    end
  end

end
